export const AUTH_EXCHANGE_RATE_WINDOW_MS = 60_000;
export const AUTH_EXCHANGE_RATE_MAX_COUNT = 10;
export const MAX_TRACKED_RATE_LIMIT_KEYS = 20_000;
export const AUTH_EXCHANGE_MAX_BODY_BYTES = 2_048;

export const TELEMETRY_RATE_WINDOW_MS = 60_000;
export const TELEMETRY_RATE_MAX_COUNT = 120;
export const TELEMETRY_MAX_BODY_BYTES = 4_096;

export const REQUEST_BODY_TIMEOUT_MS = 1_000;
